### ISSUE TITLE
1.21 Leaves服务端报错

### ISSUE THREAD

**Issue by Yamds** [Miourasaki/MotdCrape#1]
1.21 leaves服务端报错了..
![image](https://github.com/user-attachments/assets/fac3d0c5-0884-4cee-8f61-4b98d1f74820)

```
[16:26:38 INFO]: [NoTrample] Enabling NoTrample v1.3.1*
[16:26:38 ERROR]: Error occurred while enabling NoTrample v1.3.1 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.LEGACY_FARMLAND
        at java.base/java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
        at org.bukkit.Material.valueOf(Material.java:130) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.legacy.CraftLegacy.valueOf(CraftLegacy.java:238) ~[leaves-1.21.jar:1.21-9-2b772e4]
        at NoTrample-1.3.1.jar/cn.alini.notrample.NoTrampleUniversal.<init>(NoTrampleUniversal.java:23) ~[NoTrample-1.3.1.jar:?]
        at NoTrample-1.3.1.jar/cn.alini.notrample.NoTrample.onEnable(NoTrample.java:21) ~[NoTrample-1.3.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[leaves-1.21.jar:1.21-9-2b772e4]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[leaves-1.21.jar:1.21-9-2b772e4]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:633) ~[leaves-1.21.jar:1.21-9-2b772e4]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:582) ~[leaves-1.21.jar:1.21-9-2b772e4]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:751) ~[leaves-1.21.jar:1.21-9-2b772e4]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:510) ~[leaves-1.21.jar:1.21-9-2b772e4]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:331) ~[leaves-1.21.jar:1.21-9-2b772e4]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1219) ~[leaves-1.21.jar:1.21-9-2b772e4]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[leaves-1.21.jar:1.21-9-2b772e4]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[16:26:38 INFO]: [NoTrample] Disabling NoTrample v1.3.1
```

**Comment by Yamds** [comment]
抱歉，才看到论坛里提到还不支持bukkit (〃＞目＜)

**Comment by Miourasaki** [comment]
我懒，我最近不在写这个，抱歉现在还没支持ヽ(*。>Д<)o゜
